---
title: "apriori-rule"
author: "Stephen K. Ng'etich"
date: "8/11/2021"
output: html_document
---

## Prerequisite

### Linux program
R-base
build-essential

### R Packages

|package|Function|
|.......|........|
|arules|provides the infrastructure for representing, manipulating, and analyzing transaction data and patterns.|
|arulesViz|package is used for visualizing Association Rules and Frequent Itemsets. It extends the package `arules` with various visualization techniques for association rules and itemsets. The package also includes several interactive visualizations for rule exploration.|
|RColorBrewer|ColorBrewer Palette which provides color schemes for maps and other graphics.|


`devtools::install_github("mhahsler/arulesViz")` to install aruleViz library


```{r}

library(arules)
library(arulesViz)
library(RColorBrewer)


```



#Assosiation Mining Rule
## Apriori Mining rule

### Load Dataset

```{R}

#data_set = read.csv('dataset.csv')
trans<-read.transactions(file='dataset.csv', format="basket", sep="," ,header= TRUE)
inspect(head(trans,3))


```
### Applying apriori() function
```{R}
#rules <- apriori(trans, parameter = list(supp = 0.0001, conf = 0.5))
rules<-apriori(trans,parameter=list(support=0.06, confidence=0.5,minlen=3,maxlen=6)) 




```

### Applying inspect() function

```{R}
inspect(rules[20:30])

```

### Using itemFrequencyPlot() function

```{R}

arules::itemFrequencyPlot(trans, topN = 20, 
                          col = brewer.pal(8, 'Pastel2'),
                          main = 'Relative Item Frequency Plot',
                          type = "relative",
                          ylab = "Item Frequency (Relative)")

```

```{R}
sorted_rules = sort(rules, by="support", decreasing = TRUE)
inspect(sorted_rules)
#plot(sorted_rules[1:20], method = 'graph', engine = 'interactive', shading = "confidence")
plot(sorted_rules[1:20], method = "grouped matrix", engine = "htmlwidget")
plot(sorted_rules[1:20], method = "matrix", engine = "htmlwidget")
plot(sorted_rules[1:20], method = "graph", engine = "htmlwidget", data=trans)


```
